apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
stringData:
  aws-secret-name: "redshift!redshift-etlkube-redshift-admin"
  aws-region: "ap-southeast-1"
---
apiVersion: v1
kind: Secret
metadata:
  name: redshift-connection
type: Opaque
stringData:
  redshift-host: "redshift-etlkube.cmlzubnbirp1.ap-southeast-1.redshift.amazonaws.com:5439/dev"
  redshift-port: "5439"
  redshift-database: "dev"
  redshift-user: "redshift-admin"